//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 2016-07-15 16:10:08
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using DapperExtensions.Mapper;
namespace FPJ.Model.Default
{   
		 /// <summary>
		///实体-Orders 
		/// <summary>
		public partial class Orders
		{
			
				 /// <summary>
				///  
				/// </summary>
				public int  Id {get;set;}
				
				 /// <summary>
				///  
				/// </summary>
				public int  UserId {get;set;}
								
		}
	
		public partial class OrdersMapper:ClassMapper<Orders>
		{
			public OrdersMapper()
			{
        			Map(a=>a.Id).Key(KeyType.Identity);
          			AutoMap();
			}
		}
}
