//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 2016-08-02 17:36:57
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using DapperExtensions.Mapper;
namespace FPJ.Model.Default
{   
		 /// <summary>
		///实体-T1 
		/// <summary>
		public partial class T1
		{
			
				 /// <summary>
				///  
				/// </summary>
				public long  Id {get;set;}
				
				 /// <summary>
				///  
				/// </summary>
				public DateTime ? CTime {get;set;}
								
		}
	
		public partial class T1Mapper:ClassMapper<T1>
		{
			public T1Mapper()
			{
        			Map(a=>a.Id).Key(KeyType.Assigned);
          			AutoMap();
			}
		}
}
